/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.sarainfras.caillou15.utilities;

import java.util.List;

public class StringUtils {
    private StringUtils(){}

    public static String join(List source) {
        return JoinUtils.join(source);
    }

    public static List split(String source) {
        return SplitUtils.split(source);
    }
}
