/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.sarainfras.caillou15.app;

import org.junit.jupiter.api.Test;

class MessageUtilsTest {
    @Test void testGetMessage() {
        //assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
