/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.sarainfras.caillou15.app;

public class App {
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(AppWindow::new);
    }
}
